# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tim Henry's Blog
email: tim.jim.hank@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 You've found my Github Page!
 I hope to flesh this out very soon with personal projects and technology topics!
 This site is very much under construction, so please pardon my dust!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://timjimhank.github.io/" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
